server:
  port: 8080
  servlet:
    context-path: /bst
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: BST
  profiles:
    active: dev
#
# logging
#
logging:
  #path: /opt
  path: /var/log/bst/log
  level:
    root: "INFO"